# -*- coding: utf-8 -*-
"""tas_kagit_makas_OYKU_UZATICI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oJOmuqL-yobpiXzNJ-tlX9tuZpSSbcFm
"""

import random

def tas_kagit_makas_OYKU_UZATICI():

    #İlk olarak oyuna giriş yapılır. Oyuncuya oynun tanıtımı yapılır.
    print("Taş kağıt makas oyununa hoş geldiniz!😎\n1️⃣Oyun bilgisayar ve kullanıcı arasında oynanacaktır.\n2️⃣ turu kazanan kişi oyunu kazanır.\n3️⃣Oyuncular her turda taş, kağıt veya makas üçlüsünden birisini seçmesi gerekmektedir.\n4️⃣ 🔹\nTAŞ🪨-MAKAS✂ => KAZANAN TAŞ🪨\n🔹TAŞ🪨-KAĞIT📄 => KAZANAN KAĞIT📄\n🔹MAKAS✂-KAĞIT📄 => KAZANAN MAKAS✂\n🔹İKİ AYNI HAREKET => BERABERE\n5️⃣Daha sonra tekrardan oynamak isterseniz oyun bittikten sonra ekrana gelen soruya 'evet',\neğer istemezseniz 'hayır' diyebilirsiniz.\nTüm kuralları okuduğunuza göre keyifli oyunlar dileriz!🎉")
    oyun = 0

    #Oyun başlar.
    while True:
        oyun += 1
        print(f"{oyun}. oyun başlıyor!▶️🎮", flush=True)
        sayac = 1
        berabere = bilgisayar = kullanici = 0

        while kullanici < 2 and bilgisayar < 2:
            #Değerler ekrana gelir.
            print("1. değer: taş🪨\n2. değer: kağıt📄\n3. değer: makas✂", flush=True)

            hareketler = ["taş🪨", "kağıt📄", "makas ✂"]

            while True:
                try:
                    #Hatalı değer girişi yapıldığı zaman hata verir ve doğru bir değer girişi yapılması istenir.
                    hareket_deger_kullanici = int(input("Lütfen yapmak istediğiniz hamlenin değer sayısını seçiniz \n(örnek: taş seçmek için 1 yazınız.): "))
                    if hareket_deger_kullanici in [1, 2, 3]:
                        break
                    else:
                        print("Geçersiz değer. Lütfen 1, 2 veya 3 giriniz.")
                except ValueError:
                    print("Lütfen geçerli bir sayı giriniz.")

            #Kullanıcının ve bilgisayarın hareketleri ekrana gelir.
            hareket_kullanici = hareketler[hareket_deger_kullanici - 1]
            print(f"Kullanıcının {sayac}. turda seçtiği hamle:", hareket_kullanici)

            hareket_deger_bilgisayar = random.randint(1, 3)
            hareket_bilgisayar = hareketler[hareket_deger_bilgisayar - 1]
            print(f"Bilgisayarın {sayac}. turda seçtiği hamle:", hareket_bilgisayar)

            #Turda kazanan yarışmacı ekrana gelir.
            if hareket_deger_kullanici == hareket_deger_bilgisayar:
                berabere += 1
                print(f"{sayac}. turda sonuç: BERABERE! => Kullanıcı= {kullanici} Bilgisayar= {bilgisayar}")
            elif (hareket_deger_kullanici == 1 and hareket_deger_bilgisayar == 3) or \
                 (hareket_deger_kullanici == 2 and hareket_deger_bilgisayar == 1) or \
                 (hareket_deger_kullanici == 3 and hareket_deger_bilgisayar == 2):
                kullanici += 1
                print(f"{sayac}. turda kazanan: KULLANICI! 👤🎉 => Kullanıcı= {kullanici} Bilgisayar= {bilgisayar}")
            else:
                bilgisayar += 1
                print(f"{sayac}. turda kazanan: BİLGİSAYAR! 💻🎉 => Kullanıcı= {kullanici} Bilgisayar= {bilgisayar}")

            sayac += 1

        #Toplam oynanan tur ve oyun skorları ekrana gelir.
        print("Toplam oynanan tur🎮 =", sayac - 1)
        print(f"{oyun}. Oyun sonucu📊 => Kullanıcı= {kullanici} Bilgisayar= {bilgisayar}")

        #Oyun sonunda kazanan yarışmacı ekrana gelir.
        if kullanici == 2:
            print("KAZANAN KULLANICI! 👤1️⃣🏆🎉")
        elif bilgisayar == 2:
            print("KAZANAN BİLGİSAYAR! 💻1️⃣🏆🎉")

        #Tekrardan oyun oynanması için yarışmacıların fikri alınır.
        #Eğer her iki yarışmacı aynı fikirde ise yeni oyuna başlanır.
        devam_kullanici = input("Oyunu tekrardan oynamak ister misiniz (evet/hayır)?")
        if devam_kullanici.lower()=="evet":
            devam_kullanici="evet✔️"
        elif devam_kullanici.lower()=="hayır":
            devam_kullanici="hayır❌"
        else:
            devam_kullanici=input("Lütfen tekrardan uygun bir değer giriniz.Oyunu tekrardan oynamak ister misiniz (evet/hayır)?")

        devam_bilgisayar = "evet✔️" if random.randint(0, 1) == 1 else "hayır❌"
        print("Bilgisayara da aynı soruyu sorduk. Alınan cevap:", devam_bilgisayar)

        if devam_kullanici.lower() == "evet✔️" and devam_bilgisayar == "evet✔️":
            print("Oyun yeniden başlatılıyor...▶️🎮")
            continue
        else:
            print("Bir taraf veya her iki taraf da oynu istemediği için oyun sona erdi.😞 Tekrardan görüşmek üzere!👋")
            break

#Oynun oynanması için fonksiyon çağrılır.
tas_kagit_makas_OYKU_UZATICI()